In [20]:
import numpy as np
from numpy.random import randn
import matplotlib as mpl
import matplotlib.pyplot as plt
from scipy import stats
from pandas.core.frame import DataFrame

import os

from JointAngel import *

# %matplotlib inline

In [21]:
def get_result(train,test):
    root='../result/'
    f1='%d_%d.txt'%(train,test)
    files=os.listdir(root)
    if f1 not in files:
        main(train,test)
    with open(root+f1) as f:
        context=f.read()
        context=eval(context)
    return context[:1000]

In [22]:
def show_one(train,test,types=['angle_acc','angle_gyr']):
    res=get_result(train,test)
    data=[]
    colors=['green','red','blue']
    x=list(range(len(res)))
    for i in range(len(types)):
        data.append([])
    for i in range(len(res)):
        for j in range(len(types)):
            data[j].append(res[i][types[j]])
    plt.figure(19)
    for i in range(len(types)):
        plt.subplot(len(types),1,i+1)
        plt.plot(x,data[i],color=colors[i],label=types[i])
        plt.legend()
        plt.xlabel('0.01s')
        plt.ylabel('angle')
    
    plt.savefig('../image/%d-%d.jpg'%(train,test))
    plt.close()

In [26]:
for i in range(15):
    show_one(i+1,i+1)

i=0, mes:0.217125
i=1, mes:0.246624
i=2, mes:0.234268
i=3, mes:0.275173
i=4, mes:0.284096
i=5, mes:0.299414
i=6, mes:0.209587
i=7, mes:0.272327
i=8, mes:0.256017
i=9, mes:0.258254
i=10, mes:0.197047
i=11, mes:0.322195
i=12, mes:0.249769
i=13, mes:0.234324
i=14, mes:0.197320
i=15, mes:0.267442
i=16, mes:0.231780
i=17, mes:0.272796
i=18, mes:0.285272
i=19, mes:0.306814
i=20, mes:0.213197
i=21, mes:0.177117
i=22, mes:0.132096
i=23, mes:0.131430
i=24, mes:0.131314
i=25, mes:0.130866
i=26, mes:0.130677
i=27, mes:0.130406
i=28, mes:0.130281
i=29, mes:0.130146
j1,j2:
[[ 0.84033486]
 [ 0.99197324]
 [-0.49981431]]
[[ 0.97360275]
 [-0.21427021]
 [-0.07865092]]
i=0, mes:9.249824
i=1, mes:0.048194
i=2, mes:0.012144
i=3, mes:0.008435
i=4, mes:0.007970
i=5, mes:0.007935
i=6, mes:0.007933
均方根误差更新过小，已收敛
[[ 0.00729487]
 [-0.00208523]
 [-0.00449543]] [[-0.00661278]
 [-0.00061604]
 [-0.00574521]]
angle_acc_gyr: 129.75226394018233
angle_acc: 142.5750717446504
angle_acc_gyr: 129.45829365325105
angle_acc: 1

angle_acc_gyr: 123.84435788299301
angle_acc: 141.88764362976676
angle_acc_gyr: 124.00690542621372
angle_acc: 141.368879321224
angle_acc_gyr: 124.14653514172231
angle_acc: 139.21870322988977
angle_acc_gyr: 124.23710131464483
angle_acc: 134.46277704943773
angle_acc_gyr: 124.33088800722649
angle_acc: 134.90327805629735
angle_acc_gyr: 124.46468764435845
angle_acc: 139.13905404878417
angle_acc_gyr: 124.64591775450437
angle_acc: 144.23365976562172
angle_acc_gyr: 124.85173973569073
angle_acc: 147.2545953825342
angle_acc_gyr: 125.0986772576081
angle_acc: 151.94061816493326
angle_acc_gyr: 125.34282966961493
angle_acc: 152.3285845499424
angle_acc_gyr: 125.51786058066303
angle_acc: 145.9883440663479
angle_acc_gyr: 125.64048182463246
angle_acc: 141.07349947918243
angle_acc_gyr: 125.72431156936523
angle_acc: 137.33564327168025
angle_acc_gyr: 125.7967133460471
angle_acc: 136.17805337860176
angle_acc_gyr: 125.8831245018275
angle_acc: 137.48905464844708
angle_acc_gyr: 125.94341708541006
angle_acc: 134

angle_acc_gyr: 114.10014336970133
angle_acc: 129.46234866281785
angle_acc_gyr: 114.20729949910796
angle_acc: 124.23677459136158
angle_acc_gyr: 114.30645628893164
angle_acc: 123.56443947217278
angle_acc_gyr: 114.36175236111872
angle_acc: 119.20779710697359
angle_acc_gyr: 114.37465849272287
angle_acc: 114.93274931126822
angle_acc_gyr: 114.38956773803646
angle_acc: 115.02413293061235
angle_acc_gyr: 114.34541627125904
angle_acc: 109.03455752523467
angle_acc_gyr: 114.34188183806468
angle_acc: 113.05468827212546
angle_acc_gyr: 114.42026244018183
angle_acc: 121.0548054057962
angle_acc_gyr: 114.52991300613807
angle_acc: 124.05351982193385
angle_acc_gyr: 114.65596555368826
angle_acc: 125.47277994221548
angle_acc_gyr: 114.75242677653057
angle_acc: 122.23404196597303
angle_acc_gyr: 114.83733457624517
angle_acc: 120.74738823317941
angle_acc_gyr: 114.92401089111898
angle_acc: 120.38435678974925
angle_acc_gyr: 115.0199377368767
angle_acc: 120.8509520519112
angle_acc_gyr: 115.10544784633642
angle_acc

angle_acc_gyr: 112.86942501774473
angle_acc: 117.88398906025263
angle_acc_gyr: 112.96952313202898
angle_acc: 123.20544376290184
angle_acc_gyr: 113.0238238225895
angle_acc: 118.10745638683964
angle_acc_gyr: 113.13198728335945
angle_acc: 123.01224316971894
angle_acc_gyr: 113.33582359890816
angle_acc: 132.38414854906216
angle_acc_gyr: 113.54499786143292
angle_acc: 132.97988090809278
angle_acc_gyr: 113.82267161018702
angle_acc: 140.1321129973319
angle_acc_gyr: 114.08777772351222
angle_acc: 139.23592296900796
angle_acc_gyr: 114.29505883250484
angle_acc: 133.79994752117804
angle_acc_gyr: 114.49514050358206
angle_acc: 133.397263939719
angle_acc_gyr: 114.70781225505547
angle_acc: 135.01473093920544
angle_acc_gyr: 114.9428744180682
angle_acc: 137.69754030880594
angle_acc_gyr: 115.21617209142744
angle_acc: 141.94423219693797
angle_acc_gyr: 115.51284276249403
angle_acc: 144.66217448455663
angle_acc_gyr: 115.77183541689142
angle_acc: 141.22136114602608
angle_acc_gyr: 115.99489147670505
angle_acc: 

angle_acc_gyr: 116.05725104734584
angle_acc: 142.573458850603
angle_acc_gyr: 116.26143579426888
angle_acc: 134.88717963682979
angle_acc_gyr: 116.36693901803115
angle_acc: 125.39185423892758
angle_acc_gyr: 116.40709293543489
angle_acc: 118.73435638571225
angle_acc_gyr: 116.41330120368383
angle_acc: 114.88874299992972
angle_acc_gyr: 116.42803477206078
angle_acc: 115.27150603608393
angle_acc_gyr: 116.40954642468829
angle_acc: 111.61302812635068
angle_acc_gyr: 116.40895732359168
angle_acc: 113.2399344579976
angle_acc_gyr: 116.47016033835344
angle_acc: 119.4438069867529
angle_acc_gyr: 116.53071990950671
angle_acc: 119.52211944306134
angle_acc_gyr: 116.5682925391472
angle_acc: 117.3499067888854
angle_acc_gyr: 116.59255856864831
angle_acc: 116.1078544506727
angle_acc_gyr: 116.58055797297685
angle_acc: 112.5651152911628
angle_acc_gyr: 116.45931472793654
angle_acc: 101.70336872874825
angle_acc_gyr: 116.31200870587963
angle_acc: 98.91310777270628
angle_acc_gyr: 116.43096467567604
angle_acc: 125.

angle_acc_gyr: 112.17050017027732
angle_acc: 141.33572861207503
angle_acc_gyr: 112.42984701876267
angle_acc: 137.51200003940417
angle_acc_gyr: 112.70638404595107
angle_acc: 139.51965935117474
angle_acc_gyr: 112.98957576036618
angle_acc: 140.57241307458736
angle_acc_gyr: 113.21612773569174
angle_acc: 135.20539832788214
angle_acc_gyr: 113.40331129194443
angle_acc: 131.45093841150376
angle_acc_gyr: 113.64305230673936
angle_acc: 136.8496647282686
angle_acc_gyr: 113.99382970420902
angle_acc: 148.20436279725806
angle_acc_gyr: 114.4224102535753
angle_acc: 156.42614000453182
angle_acc_gyr: 114.8752310392602
angle_acc: 159.31944365049878
angle_acc_gyr: 115.28292580047082
angle_acc: 155.24506442478366
angle_acc_gyr: 115.66809738263697
angle_acc: 153.33370296174925
angle_acc_gyr: 116.00275561004294
angle_acc: 148.42025259414257
angle_acc_gyr: 116.23799754402904
angle_acc: 138.4907095573609
angle_acc_gyr: 116.45811541017878
angle_acc: 137.02604980635581
angle_acc_gyr: 116.66318979938325
angle_acc:

i=0, mes:0.370930
i=1, mes:0.443046
i=2, mes:0.446410
i=3, mes:0.413776
i=4, mes:0.315696
i=5, mes:0.310737
i=6, mes:0.326797
i=7, mes:0.526985
i=8, mes:0.368162
i=9, mes:0.533196
i=10, mes:0.359243
i=11, mes:0.594874
i=12, mes:0.355313
i=13, mes:0.673385
i=14, mes:0.390110
i=15, mes:0.627552
i=16, mes:0.331309
i=17, mes:0.611349
i=18, mes:0.349032
i=19, mes:0.484864
i=20, mes:0.345265
i=21, mes:0.486108
i=22, mes:0.350835
i=23, mes:0.464762
i=24, mes:0.350649
i=25, mes:0.464317
i=26, mes:0.350746
i=27, mes:0.463842
i=28, mes:0.350741
i=29, mes:0.463821
j1,j2:
[[ 0.87858353]
 [-0.84165756]
 [-0.437833  ]]
[[0.99070638]
 [0.08427182]
 [0.10676674]]
i=0, mes:17.381386
i=1, mes:0.092579
i=2, mes:0.040896
i=3, mes:0.037310
i=4, mes:0.036613
i=5, mes:0.036420
i=6, mes:0.036415
均方根误差更新过小，已收敛
[[ 0.00096427]
 [-0.0033928 ]
 [-0.00438568]] [[-0.00804094]
 [ 0.00181033]
 [-0.00431107]]
angle_acc_gyr: 140.9506246093574
angle_acc: 138.26650822990388
angle_acc_gyr: 140.9237694209001
angle_acc: 138.

angle_acc: 99.25606905338003
angle_acc_gyr: 121.62436348749794
angle_acc: 94.06775692004389
angle_acc_gyr: 121.30333040043841
angle_acc: 89.25041610556136
angle_acc_gyr: 120.93942584628064
angle_acc: 84.82659518210536
angle_acc_gyr: 120.5831318976487
angle_acc: 85.30443939483011
angle_acc_gyr: 120.27121602723518
angle_acc: 89.3814217261327
angle_acc_gyr: 120.117513170601
angle_acc: 104.73934994548384
angle_acc_gyr: 120.04531461696473
angle_acc: 112.3289528032419
angle_acc_gyr: 119.97061815078344
angle_acc: 111.4558438801312
angle_acc_gyr: 119.93024873892936
angle_acc: 114.50249378843071
angle_acc_gyr: 119.80549816497852
angle_acc: 105.85115342800746
angle_acc_gyr: 119.66993082999555
angle_acc: 104.57414897896591
angle_acc_gyr: 119.51035830335756
angle_acc: 102.02201645328186
angle_acc_gyr: 119.32131350005054
angle_acc: 98.93364796585087
angle_acc_gyr: 119.11541611788073
angle_acc: 97.07441609973625
angle_acc_gyr: 118.91520452799247
angle_acc: 97.45101067973395
angle_acc_gyr: 118.714720

angle_acc_gyr: 101.79372143935535
angle_acc: 141.23767787668206
angle_acc_gyr: 102.16033973076571
angle_acc: 139.99809174001157
angle_acc_gyr: 102.52178928235395
angle_acc: 138.36273192358104
angle_acc_gyr: 102.59679464014361
angle_acc: 108.68454656693193
angle_acc_gyr: 102.02958915548058
angle_acc: 43.8077388275213
angle_acc_gyr: 101.16618977285596
angle_acc: 13.528854697294713
angle_acc_gyr: 100.33445961915965
angle_acc: 16.210516499691806
angle_acc_gyr: 100.02978764236303
angle_acc: 68.35615653004575
angle_acc_gyr: 99.57933519115059
angle_acc: 52.98861653257599
angle_acc_gyr: 99.24900084959161
angle_acc: 63.72800420085877
angle_acc_gyr: 99.29753365417226
angle_acc: 100.99464052059187
angle_acc_gyr: 100.05820557097587
angle_acc: 172.80317081331916
angle_acc_gyr: 100.60931933222074
angle_acc: 153.56511072908532
angle_acc_gyr: 100.90956757345057
angle_acc: 130.18906003271061
angle_acc_gyr: 101.168803405749
angle_acc: 127.59020851749418
angle_acc_gyr: 101.90227350206575
angle_acc: 176.0

angle_acc_gyr: 100.13264931306479
angle_acc: 176.9438692374192
angle_acc_gyr: 100.24866032022963
angle_acc: 109.58700543915675
angle_acc_gyr: 100.32288245773161
angle_acc: 106.99919750729488
angle_acc_gyr: 100.57548927087925
angle_acc: 126.01056275601385
angle_acc_gyr: 100.92502309811954
angle_acc: 136.83254599662817
angle_acc_gyr: 101.01695158553954
angle_acc: 112.11642709823236
angle_acc_gyr: 100.40646588778762
angle_acc: 41.51057447454935
angle_acc_gyr: 99.54552765323477
angle_acc: 15.141275650186758
angle_acc_gyr: 99.10830088559945
angle_acc: 56.131228056378944
angle_acc_gyr: 99.28122325565295
angle_acc: 116.5666504153002
angle_acc_gyr: 99.72209084173215
angle_acc: 143.7694103807256
angle_acc_gyr: 100.07790781415493
angle_acc: 135.77066576687827
angle_acc_gyr: 100.2757638758749
angle_acc: 120.24687287635744
angle_acc_gyr: 100.36235403892964
angle_acc: 108.81029643167412
angle_acc_gyr: 100.45639381136552
angle_acc: 109.10130036411186
angle_acc_gyr: 100.6869420753933
angle_acc: 122.4

angle_acc_gyr: 106.64430990120711
angle_acc: 174.82114106082082
angle_acc_gyr: 107.28872890957963
angle_acc: 170.83001038597695
angle_acc_gyr: 107.9389316667155
angle_acc: 172.02131022859243
angle_acc_gyr: 108.49663302870046
angle_acc: 163.3714990719977
angle_acc_gyr: 108.94996102109835
angle_acc: 153.4552438055746
angle_acc_gyr: 109.41280275680964
angle_acc: 154.8438917974151
angle_acc_gyr: 109.95605365869227
angle_acc: 163.374799154861
angle_acc_gyr: 110.40426600534269
angle_acc: 154.46455363141374
angle_acc_gyr: 110.77310299943241
angle_acc: 147.0628936683588
angle_acc_gyr: 111.03605809097733
angle_acc: 136.9733070844891
angle_acc_gyr: 111.28828425189664
angle_acc: 136.29148322950684
angle_acc_gyr: 111.5643780973471
angle_acc: 139.04214890808922
angle_acc_gyr: 111.81448992317958
angle_acc: 136.78774837069503
angle_acc_gyr: 112.0523821404184
angle_acc: 135.84364517864276
angle_acc_gyr: 112.28780741842364
angle_acc: 135.81998100112605
angle_acc_gyr: 112.49097978976967
angle_acc: 132.8

angle_acc_gyr: 112.64185343363435
angle_acc: 137.65643041647314
angle_acc_gyr: 112.84547305857537
angle_acc: 132.9611410116991
angle_acc_gyr: 113.12608288864853
angle_acc: 140.76507471506577
angle_acc_gyr: 113.51579389019176
angle_acc: 151.894926127418
angle_acc_gyr: 113.97690412716852
angle_acc: 159.40006617372703
angle_acc_gyr: 114.37896138241133
angle_acc: 153.90880833167657
angle_acc_gyr: 114.65734547184155
angle_acc: 141.8516721620879
angle_acc_gyr: 114.76679351165461
angle_acc: 125.07912364770765
angle_acc_gyr: 114.83743564846527
angle_acc: 121.20827858411684
angle_acc_gyr: 114.8393517842923
angle_acc: 114.3677971491204
angle_acc_gyr: 114.83976842055185
angle_acc: 114.27042616093824
angle_acc_gyr: 114.83498362880708
angle_acc: 113.84751949984815
angle_acc_gyr: 114.77991896450752
angle_acc: 108.87533722468488
angle_acc_gyr: 114.7422016527696
angle_acc: 110.56954221610306
angle_acc_gyr: 114.63736434462615
angle_acc: 103.7894137916628
angle_acc_gyr: 114.54063613784378
angle_acc: 104

angle_acc: 121.95487459321917
angle_acc_gyr: 122.12299630515756
angle_acc: 124.45380561519988
angle_acc_gyr: 122.16606346553915
angle_acc: 125.96037135117116
angle_acc_gyr: 122.21248436560712
angle_acc: 126.52830889117523
angle_acc_gyr: 122.2349297309301
angle_acc: 124.3050492080477
angle_acc_gyr: 122.21932768035485
angle_acc: 120.61722798356759
angle_acc_gyr: 122.19867567388702
angle_acc: 120.08372749555281
angle_acc_gyr: 122.16408626379705
angle_acc: 118.60948821917593
angle_acc_gyr: 122.14146022886929
angle_acc: 119.71126869073188
angle_acc_gyr: 122.14605094363745
angle_acc: 122.39262115045752
angle_acc_gyr: 122.16733872195105
angle_acc: 124.11366919253899
angle_acc_gyr: 122.20092974486519
angle_acc: 125.45693713891157
angle_acc_gyr: 122.24535851866554
angle_acc: 126.66910476701707
angle_acc_gyr: 122.29030316961446
angle_acc: 126.86998522339975
angle_acc_gyr: 122.34911333266152
angle_acc: 128.3709299543865
angle_acc_gyr: 122.4231028007644
angle_acc: 130.0110418440128
angle_acc_gyr: 

angle_acc_gyr: 113.04776524305399
angle_acc: 121.83428041921067
angle_acc_gyr: 113.2965526486451
angle_acc: 137.45627091769057
angle_acc_gyr: 113.61891319972555
angle_acc: 145.97434989374875
angle_acc_gyr: 114.0141021616127
angle_acc: 154.63621406832274
angle_acc_gyr: 114.47824883476795
angle_acc: 163.29166166099085
angle_acc_gyr: 114.93033346307263
angle_acc: 163.66170562997274
angle_acc_gyr: 115.37422324662234
angle_acc: 164.2080662661316
angle_acc_gyr: 115.77693840520985
angle_acc: 161.07973842438557
angle_acc_gyr: 116.09876025728855
angle_acc: 153.43111182393528
angle_acc_gyr: 116.35242246281362
angle_acc: 146.5797489601492
angle_acc_gyr: 116.60960090881319
angle_acc: 146.5111533081944
angle_acc_gyr: 116.94153445958881
angle_acc: 153.48168464358056
angle_acc_gyr: 117.34275385461599
angle_acc: 159.97469719820006
angle_acc_gyr: 117.83268369030391
angle_acc: 168.5825944580531
angle_acc_gyr: 118.38418877854349
angle_acc: 174.6239502995391
angle_acc_gyr: 118.9271438241136
angle_acc: 173

angle_acc: 156.3206812968994
angle_acc_gyr: 123.06159080136737
angle_acc: 151.51246811607342
angle_acc_gyr: 123.32149509532105
angle_acc: 148.70491401190137
angle_acc_gyr: 123.5620262526747
angle_acc: 146.91133325469622
angle_acc_gyr: 123.79204604011373
angle_acc: 146.0067214426566
angle_acc_gyr: 124.0493633961859
angle_acc: 148.72920159464996
angle_acc_gyr: 124.31073043787792
angle_acc: 149.13515191723457
angle_acc_gyr: 124.56143311931544
angle_acc: 147.9672807698374
angle_acc_gyr: 124.80338177529002
angle_acc: 146.84711096465202
angle_acc_gyr: 125.0528100237439
angle_acc: 147.33493698030375
angle_acc_gyr: 125.30170426079131
angle_acc: 147.14443479176714
angle_acc_gyr: 125.60161564241349
angle_acc: 152.28261881347836
angle_acc_gyr: 125.96379769492533
angle_acc: 158.54673850072797
angle_acc_gyr: 126.2817941186711
angle_acc: 154.21265786130581
angle_acc_gyr: 126.52641896054544
angle_acc: 146.9144362146728
angle_acc_gyr: 126.75338265142177
angle_acc: 145.14045544693641
angle_acc_gyr: 126

angle_acc_gyr: 122.73897833243103
angle_acc: 122.83240736903426
angle_acc_gyr: 122.73681960878608
angle_acc: 122.62864149564871
angle_acc_gyr: 122.45074490652378
angle_acc: 94.82098254956126
angle_acc_gyr: 121.9872399570959
angle_acc: 77.06144088830507
angle_acc_gyr: 121.46110649412573
angle_acc: 70.01314258752133
angle_acc_gyr: 120.93415738250326
angle_acc: 68.6571696383258
angle_acc_gyr: 120.60244459830321
angle_acc: 86.8634363270582
angle_acc_gyr: 120.29211887003656
angle_acc: 88.26359609674336
angle_acc_gyr: 120.04324505140889
angle_acc: 93.99413533582533
angle_acc_gyr: 119.85294533472764
angle_acc: 99.79417181734568
angle_acc_gyr: 119.71418820149292
angle_acc: 105.06658234121298
angle_acc_gyr: 119.52009800553314
angle_acc: 99.92543674330557
angle_acc_gyr: 119.22133086738441
angle_acc: 89.74307375514358
angle_acc_gyr: 118.9394422909451
angle_acc: 91.22872699593992
angle_acc_gyr: 118.61787314540307
angle_acc: 86.8869057266587
angle_acc_gyr: 118.25891367505066
angle_acc: 82.642350280

angle_acc_gyr: 114.06467674538743
angle_acc: 104.0133090361404
angle_acc_gyr: 113.93517356544054
angle_acc: 102.90830229639901
angle_acc_gyr: 113.7967791370547
angle_acc: 101.27397992047358
angle_acc_gyr: 113.67101682381606
angle_acc: 101.67086459482616
angle_acc_gyr: 113.56134271969265
angle_acc: 102.51338382993
angle_acc_gyr: 113.45755434597791
angle_acc: 102.46028919719976
angle_acc_gyr: 113.37788547821171
angle_acc: 104.50647321984704
angle_acc_gyr: 113.31082365951526
angle_acc: 105.56520003305678
angle_acc_gyr: 113.23836007627987
angle_acc: 104.9486837262223
angle_acc_gyr: 113.17451243810474
angle_acc: 105.87342951525716
angle_acc_gyr: 113.12356412641334
angle_acc: 107.32294675523922
angle_acc_gyr: 113.0792352635772
angle_acc: 108.23497430580076
angle_acc_gyr: 113.02634109014758
angle_acc: 107.55203624416617
angle_acc_gyr: 112.96571859559972
angle_acc: 106.9472243370991
angle_acc_gyr: 112.90510922766244
angle_acc: 107.09809646141744
angle_acc_gyr: 112.84015555765662
angle_acc: 106

angle_acc_gyr: 8.43944096219095
angle_acc: 0.906969002886661
angle_acc_gyr: 8.3587675048168
angle_acc: 0.4450657601883389
angle_acc_gyr: 8.281403157788041
angle_acc: 0.7254060463141376
angle_acc_gyr: 8.210743811274044
angle_acc: 1.2692688103971212
angle_acc_gyr: 8.14622883886775
angle_acc: 1.713076487780326
angle_acc_gyr: 8.091030553002502
angle_acc: 2.5098525180296214
angle_acc_gyr: 8.015087496804773
angle_acc: 0.335180881616192
angle_acc_gyr: 7.9601932924697865
angle_acc: 2.3164824475211616
angle_acc_gyr: 7.914390882357637
angle_acc: 3.0865034851172646
angle_acc_gyr: 7.87546349068317
angle_acc: 3.5546036199622097
angle_acc_gyr: 7.8380803797669385
angle_acc: 3.4952367763762933
angle_acc_gyr: 7.801629432289132
angle_acc: 3.3681028410670746
angle_acc_gyr: 7.768218362745855
angle_acc: 3.456496311869087
angle_acc_gyr: 7.72272725204481
angle_acc: 2.1125574688871582
angle_acc_gyr: 7.677608954849975
angle_acc: 2.0499660766985164
angle_acc_gyr: 7.639697163501485
angle_acc: 2.7104575590020166


angle_acc_gyr: 24.361174210953884
angle_acc: 24.876090798531514
angle_acc_gyr: 24.404635991028993
angle_acc: 28.417956218612208
angle_acc_gyr: 24.53289112669069
angle_acc: 36.876909742586236
angle_acc_gyr: 24.69281091445744
angle_acc: 40.041870821200206
angle_acc_gyr: 24.833801835001275
angle_acc: 38.16381995861267
angle_acc_gyr: 24.950590683235035
angle_acc: 35.80514101501304
angle_acc_gyr: 25.06415086042994
angle_acc: 35.65409796398988
angle_acc_gyr: 25.180489387613466
angle_acc: 36.18617977583959
angle_acc_gyr: 25.322011617909688
angle_acc: 39.009179158427195
angle_acc_gyr: 25.452033531115923
angle_acc: 38.07684059721428
angle_acc_gyr: 25.535341110875596
angle_acc: 33.475687870842975
angle_acc_gyr: 25.58325529925486
angle_acc: 29.950945276392826
angle_acc_gyr: 25.616592976619184
angle_acc: 28.562772297575126
angle_acc_gyr: 25.723047283848828
angle_acc: 35.98321041860568
angle_acc_gyr: 26.13019952193977
angle_acc: 66.27122675211639
angle_acc_gyr: 27.332131679723943
angle_acc: 146.186

angle_acc_gyr: 40.11389887641132
angle_acc: 70.57938161390793
angle_acc_gyr: 40.282073918021474
angle_acc: 57.08695699990972
angle_acc_gyr: 40.548653125402886
angle_acc: 66.9907681021056
angle_acc_gyr: 41.089077397173725
angle_acc: 94.34228241775978
angle_acc_gyr: 41.667689037148946
angle_acc: 98.19177464744115
angle_acc_gyr: 41.935976193912985
angle_acc: 67.21657200240276
angle_acc_gyr: 41.912763854543826
angle_acc: 38.20454319364153
angle_acc_gyr: 41.7065199266688
angle_acc: 20.13301254905687
angle_acc_gyr: 41.55209700825919
angle_acc: 25.29716500223443
angle_acc_gyr: 41.612470708928875
angle_acc: 46.89484385100823
angle_acc_gyr: 41.643211214134965
angle_acc: 44.19155208949048
angle_acc_gyr: 41.608525890303376
angle_acc: 37.46537332118444
angle_acc_gyr: 41.54304382713352
angle_acc: 33.77132126930305
angle_acc_gyr: 41.43801742987851
angle_acc: 29.105808661720125
angle_acc_gyr: 41.35756174749544
angle_acc: 30.923938054707172
angle_acc_gyr: 41.27167829780706
angle_acc: 30.23313432397000

angle_acc_gyr: 39.579159035575984
angle_acc: 52.65758650914271
angle_acc_gyr: 39.65817196384815
angle_acc: 47.77111544385267
angle_acc_gyr: 39.69413032794312
angle_acc: 43.80650311676993
angle_acc_gyr: 39.65589189408881
angle_acc: 36.76777359310728
angle_acc_gyr: 39.58788788062394
angle_acc: 34.25720028330425
angle_acc_gyr: 39.55570720647222
angle_acc: 38.25497814837485
angle_acc_gyr: 39.62121207385801
angle_acc: 48.44629094046489
angle_acc_gyr: 39.78613780167559
angle_acc: 58.75522094680121
angle_acc_gyr: 39.955018459433624
angle_acc: 59.36230322115634
angle_acc_gyr: 40.02835531192359
angle_acc: 49.791066278345006
angle_acc_gyr: 40.059763843071494
angle_acc: 45.55399229627155
angle_acc_gyr: 40.131037716041064
angle_acc: 49.52272201962169
angle_acc_gyr: 40.251888704780264
angle_acc: 54.66879640567159
angle_acc_gyr: 40.32558512171313
angle_acc: 50.33362708674297
angle_acc_gyr: 40.312230706166304
angle_acc: 41.7871102509722
angle_acc_gyr: 40.25200333336917
angle_acc: 36.835563117940616
a

angle_acc_gyr: 47.03921145625747
angle_acc: 33.5200248908844
angle_acc_gyr: 47.1108678357537
angle_acc: 56.11550581008185
angle_acc_gyr: 46.780226096725094
angle_acc: 15.522014083913248
angle_acc_gyr: 46.461464517858815
angle_acc: 16.044496775001704
angle_acc_gyr: 46.17173099860018
angle_acc: 19.93333665498425
angle_acc_gyr: 45.96800099232621
angle_acc: 29.527658945036524
angle_acc_gyr: 46.30420009474083
angle_acc: 84.34420738390793
angle_acc_gyr: 46.642233824938316
angle_acc: 84.51666732028714
angle_acc_gyr: 47.06084197357283
angle_acc: 90.96403544810934
angle_acc_gyr: 47.553539713560724
angle_acc: 96.60550157228579
angle_acc_gyr: 47.491878207180775
angle_acc: 39.962076538370866
angle_acc_gyr: 47.317578964295706
angle_acc: 27.872205971947885
angle_acc_gyr: 47.260328274756496
angle_acc: 39.28611003504713
angle_acc_gyr: 46.99773829497597
angle_acc: 18.754103082966086
angle_acc_gyr: 46.605561924639204
angle_acc: 5.6095587546305845
angle_acc_gyr: 47.09152168406262
angle_acc: 93.4213289472

i=0, mes:0.521833
i=1, mes:0.678082
i=2, mes:0.782253
i=3, mes:0.618719
i=4, mes:1.170244
i=5, mes:0.484133
i=6, mes:0.431299
i=7, mes:0.427697
i=8, mes:0.427675
i=9, mes:0.429743
i=10, mes:0.437790
i=11, mes:0.466663
i=12, mes:0.529876
i=13, mes:0.711222
i=14, mes:0.738368
i=15, mes:0.688869
i=16, mes:0.600674
i=17, mes:0.534931
i=18, mes:1.093533
i=19, mes:1.169512
i=20, mes:0.464580
i=21, mes:0.671183
i=22, mes:0.680039
i=23, mes:0.646777
i=24, mes:0.612815
i=25, mes:1.089456
i=26, mes:0.666262
i=27, mes:1.250709
i=28, mes:0.720196
i=29, mes:0.630256
j1,j2:
[[ 0.8253582 ]
 [ 0.98413329]
 [-0.44911515]]
[[0.96419995]
 [0.12013732]
 [0.23640109]]
i=0, mes:21.312814
i=1, mes:0.067858
i=2, mes:0.020202
i=3, mes:0.018295
i=4, mes:0.018192
i=5, mes:0.018187
均方根误差更新过小，已收敛
[[ 0.00462566]
 [-0.00055856]
 [-0.00569035]] [[-0.00752102]
 [ 0.00020567]
 [-0.00389489]]
angle_acc_gyr: 104.66966870031095
angle_acc: 104.3003791014659
angle_acc_gyr: 104.67744275833752
angle_acc: 105.4214343685226
ang

angle_acc_gyr: 99.57137388697626
angle_acc: 101.12787231201933
angle_acc_gyr: 99.59394576465044
angle_acc: 99.72067041449075
angle_acc_gyr: 99.6681829841606
angle_acc: 104.96646470713637
angle_acc_gyr: 99.76662930085385
angle_acc: 107.57659227152149
angle_acc_gyr: 99.85788240528754
angle_acc: 107.07015699820394
angle_acc_gyr: 99.9831094129256
angle_acc: 110.75135043557367
angle_acc_gyr: 100.17183132619098
angle_acc: 117.58279619784328
angle_acc_gyr: 100.3422182085859
angle_acc: 116.33828235440441
angle_acc_gyr: 100.54579999104048
angle_acc: 120.14617146335904
angle_acc_gyr: 100.72447373948951
angle_acc: 118.06657961712699
angle_acc_gyr: 100.81315067672239
angle_acc: 109.35227484217351
angle_acc_gyr: 100.76661096324098
angle_acc: 95.98755732161955
angle_acc_gyr: 100.64451267738185
angle_acc: 88.44723444625387
angle_acc_gyr: 100.46598572237626
angle_acc: 82.61847769124003
angle_acc_gyr: 100.21677642426869
angle_acc: 75.2801998122272
angle_acc_gyr: 100.008537289619
angle_acc: 79.028939499

angle_acc: 52.524500662902746
angle_acc_gyr: 68.09457484201982
angle_acc: 61.72179327742951
angle_acc_gyr: 67.99015128012914
angle_acc: 60.416438820207695
angle_acc_gyr: 67.74183994714497
angle_acc: 46.57450518282376
angle_acc_gyr: 67.3590616949881
angle_acc: 33.355173778659754
angle_acc_gyr: 67.07810489988842
angle_acc: 43.42211923827442
angle_acc_gyr: 66.51480438714805
angle_acc: 14.890818523591104
angle_acc_gyr: 66.40423997050856
angle_acc: 59.20332502061825
angle_acc_gyr: 66.36818955792874
angle_acc: 65.97591083448232
angle_acc_gyr: 66.38197730917636
angle_acc: 70.47940369419628
angle_acc_gyr: 66.47374519889254
angle_acc: 77.92005233860111
angle_acc_gyr: 66.7525781690631
angle_acc: 96.39799724633494
angle_acc_gyr: 67.1872660416258
angle_acc: 112.44439114365794
angle_acc_gyr: 67.67988045786473
angle_acc: 119.25433417233228
angle_acc_gyr: 68.14555949117808
angle_acc: 117.93768622702044
angle_acc_gyr: 68.56303747541291
angle_acc: 114.50620677204063
angle_acc_gyr: 68.97182385205974
ang

angle_acc_gyr: 89.09277880594463
angle_acc: 106.69694808119604
angle_acc_gyr: 89.28404800113236
angle_acc: 106.0745929483769
angle_acc_gyr: 89.43121747451228
angle_acc: 101.69008197529051
angle_acc_gyr: 89.53675570495352
angle_acc: 97.2187770543629
angle_acc_gyr: 89.5566112124962
angle_acc: 88.12860268799048
angle_acc_gyr: 89.51866810646301
angle_acc: 81.75682180532574
angle_acc_gyr: 89.55431601910696
angle_acc: 88.59878719540933
angle_acc_gyr: 89.83998023535872
angle_acc: 113.22996426636116
angle_acc_gyr: 90.26607426361028
angle_acc: 127.42770724134009
angle_acc_gyr: 90.59846785705875
angle_acc: 118.5411061887377
angle_acc_gyr: 90.94868708157436
angle_acc: 120.85824131911276
angle_acc_gyr: 90.18730495609363
angle_acc: 10.429646256437078
angle_acc_gyr: 89.71516408262957
angle_acc: 38.681813604841864
angle_acc_gyr: 89.13052317349656
angle_acc: 28.299260886904225
angle_acc_gyr: 88.8965181007676
angle_acc: 65.40890858712997
angle_acc_gyr: 88.72615317559504
angle_acc: 72.38842172270398
ang

angle_acc_gyr: 82.62863320674234
angle_acc: 111.68025181159601
angle_acc_gyr: 83.14949084286731
angle_acc: 131.0502819873505
angle_acc_gyr: 83.86381495623858
angle_acc: 152.12065663292304
angle_acc_gyr: 84.75123113618638
angle_acc: 171.16395356511592
angle_acc_gyr: 84.45687296566926
angle_acc: 54.95288396461302
angle_acc_gyr: 83.92748580317213
angle_acc: 32.16151321720375
angle_acc_gyr: 83.13729098416864
angle_acc: 6.0235279307103395
angle_acc_gyr: 82.33708003272437
angle_acc: 4.312469657734047
angle_acc_gyr: 81.58661109123247
angle_acc: 8.394156112885527
angle_acc_gyr: 80.94853072904554
angle_acc: 18.8911716814601
angle_acc_gyr: 80.41551125017709
angle_acc: 28.854155712883912
angle_acc_gyr: 79.94197113633
angle_acc: 34.462175405961915
angle_acc_gyr: 79.45203593153312
angle_acc: 32.412073590312005
angle_acc_gyr: 78.9825576763423
angle_acc: 33.68386171616572
angle_acc_gyr: 78.43223702684897
angle_acc: 24.7570394092376
angle_acc_gyr: 77.76932642907626
angle_acc: 12.658854408368402
angle_

angle_acc_gyr: 71.23884425520997
angle_acc: 3.374374526417496
angle_acc_gyr: 70.54688014062492
angle_acc: 2.1875159294461204
angle_acc_gyr: 69.86972906568404
angle_acc: 2.8784019512957983
angle_acc_gyr: 69.2768420000921
angle_acc: 10.535220027420918
angle_acc_gyr: 68.75424037605453
angle_acc: 16.91541419252368
angle_acc_gyr: 68.34734962046768
angle_acc: 27.9695842622334
angle_acc_gyr: 67.98072217542962
angle_acc: 31.538854807171003
angle_acc_gyr: 67.54829406212133
angle_acc: 24.505746092729968
angle_acc_gyr: 67.13637244084197
angle_acc: 26.021522263749073
angle_acc_gyr: 66.84402262156622
angle_acc: 37.40925407028864
angle_acc_gyr: 66.5934240462019
angle_acc: 41.1618386384117
angle_acc_gyr: 66.33997669505459
angle_acc: 40.57770630597448
angle_acc_gyr: 66.13882162991307
angle_acc: 45.54644310322552
angle_acc_gyr: 66.04740970518948
angle_acc: 56.3392076987439
angle_acc_gyr: 65.90994383103296
angle_acc: 51.62744227265959
angle_acc_gyr: 65.7078274813234
angle_acc: 45.05015948097847
angle_ac

KeyboardInterrupt: 

In [27]:
a=get_result(1,1)

In [28]:
a

[{'angle_acc_gyr': 129.75226394018233,
  'angle_acc': 142.5750717446504,
  'angle_gyr': -0.00010365642824073398},
 {'angle_acc_gyr': 129.45829365325105,
  'angle_acc': 100.35436058306965,
  'angle_gyr': -9.48214384940149e-05},
 {'angle_acc_gyr': 129.10821039947706,
  'angle_acc': 94.53490733014043,
  'angle_gyr': -0.0009527916838314388},
 {'angle_acc_gyr': 128.87584770392507,
  'angle_acc': 105.97171043000569,
  'angle_gyr': -0.001960565277015602},
 {'angle_acc_gyr': 128.62685776739886,
  'angle_acc': 104.06714386708123,
  'angle_gyr': -0.0028725836182014707},
 {'angle_acc_gyr': 128.33115526788174,
  'angle_acc': 99.14497107131594,
  'angle_gyr': -0.003765141755891589},
 {'angle_acc_gyr': 128.05427834857986,
  'angle_acc': 100.7266885696308,
  'angle_gyr': -0.004605800664326004},
 {'angle_acc_gyr': 127.80603158020963,
  'angle_acc': 103.27239960585892,
  'angle_gyr': -0.005038104647184877},
 {'angle_acc_gyr': 127.54407265093823,
  'angle_acc': 101.62375638775362,
  'angle_gyr': -0.0051

In [3]:
for i in range(1,1):
    print(i)

In [43]:
data=[]
for i in range(10):
    data.append([2,4,5,6])
# MovAvg(data,[2,3],window_size=3)

In [35]:
data

[[2, 4, 5.0, 6.0],
 [2, 4, 5.0, 6.0],
 [2, 4, 5.0, 6.0],
 [2, 4, 5.0, 6.0],
 [2, 4, 5.0, 6.0],
 [2, 4, 5.0, 6.0],
 [2, 4, 5.0, 6.0],
 [2, 4, 5.0, 6.0],
 [2, 4, 5.0, 6.0],
 [2, 4, 5.0, 6.0]]

In [45]:
data=list(map(list, zip(*data)))

In [46]:
data

[[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
 [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
 [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0],
 [6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0]]

In [47]:
MovAvg(data,[2,3],window_size=2)

[[2, 2, 3.6666666666666665, 3.6666666666666665, 2, 2, 2, 2, 2, 2],
 [4, 4, 4.25, 4.25, 4, 4, 4, 4, 4, 4],
 [5.0, 5.0, 4.25, 4.25, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0],
 [6.0, 6.0, 5.0, 5.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0]]

In [39]:
from JointAngel import MovAvg

In [41]:
MovAvg(data,[2,3],window_size=2)

[[2, 2, 4.212962962962963, 4.212962962962963, 2, 2, 2, 2, 2, 2],
 [4, 4, 4.284722222222221, 4.284722222222221, 4, 4, 4, 4, 4, 4],
 [5.0,
  5.0,
  4.284722222222221,
  4.284722222222221,
  5.0,
  5.0,
  5.0,
  5.0,
  5.0,
  5.0],
 [6.0,
  6.0,
  4.361111111111111,
  4.361111111111111,
  6.0,
  6.0,
  6.0,
  6.0,
  6.0,
  6.0]]